// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2024 - present Mikael Sundell
// https://github.com/mikaelsundell/flipman

#pragma once

#include <flipmansdk/flipmansdk.h>
#include <flipmansdk/core/imagebuffer.h>
#include <flipmansdk/render/renderspec.h>
#include <QMetaType>

namespace flipman::sdk::render {

class RenderOutputPrivate;

/**
 * @class RenderOutput
 * @brief Base class for render output handlers.
 *
 * RenderOutput describes an additional render destination handled by the render
 * engine. It stores the render pass description, output delivery format, and
 * readback requirements for destinations such as DeckLink devices, file
 * writers, streaming backends, or offscreen consumers.
 *
 * The render specification describes where and how the rendered image should be
 * produced. The output format describes the final delivery/readback format
 * expected by the output handler.
 */
class FLIPMANSDK_EXPORT RenderOutput : public QObject {
public:
    /**
     * @enum Format
     * @brief Requested delivery format for this output.
     *
     * The render engine may render through an internal intermediate format,
     * such as RGBA16F, before converting to the requested output format.
     */
    enum class Format {
        RGBA16F,  ///< Half-float RGBA output.
        RGBA8,    ///< 8-bit RGBA output.
        UYVY8,    ///< 8-bit 4:2:2 UYVY / 2vuy output.
        V210      ///< 10-bit 4:2:2 v210 output.
    };

public:
    /**
     * @brief Constructs a render output.
     */
    explicit RenderOutput(QObject* parent = nullptr);

    /**
     * @brief Destroys the render output.
     */
    virtual ~RenderOutput();

    /**
     * @brief Returns whether this output is enabled.
     */
    bool enabled() const;

    /**
     * @brief Enables or disables this output.
     */
    void setEnabled(bool enabled);

    /**
     * @brief Returns the requested delivery format for this output.
     */
    Format format() const;

    /**
     * @brief Sets the requested delivery format for this output.
     */
    void setFormat(Format format);

    /**
     * @brief Returns the render pass description used by this output.
     */
    RenderSpec pass() const;

    /**
     * @brief Sets the render pass description used by this output.
     */
    void setRenderSpec(const RenderSpec& renderSpec);

    /**
     * @brief Receives a completed CPU-readable frame from the render engine.
     *
     * The default implementation does nothing. Derived output types can override
     * this to enqueue, write, transmit, or display a rendered frame.
     *
     * This function is called only for outputs where readback() is enabled.
     *
     * @param image Rendered frame data in the requested output format.
     * @param frame Monotonic frame index generated by the render engine.
     */
    virtual void enqueueFrame(const core::ImageBuffer& image, qint64 frame);

private:
    Q_DISABLE_COPY_MOVE(RenderOutput)
    QScopedPointer<RenderOutputPrivate> p;
};

}  // namespace flipman::sdk::render

/**
 * @note Registering the type for use in QVariant.
 */
Q_DECLARE_METATYPE(flipman::sdk::render::RenderOutput*)
