// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2024 - present Mikael Sundell
// https://github.com/mikaelsundell/flipman

#pragma once

#include <flipmansdk/flipmansdk.h>
#include <flipmansdk/core/imagebuffer.h>
#include <flipmansdk/render/renderspec.h>
#include <QMetaType>

namespace flipman::sdk::render {

class RenderOutputPrivate;

/**
 * @class RenderOutput
 * @brief Base class for render output handlers.
 *
 * Stores a render pass description and provides a hook for receiving completed
 * frame data after GPU rendering and readback. Derived output types can use
 * enqueueFrame() to submit frames to external destinations such as DeckLink,
 * file writers, or streaming backends.
 */
class FLIPMANSDK_EXPORT RenderOutput {
public:
    /**
     * @brief Constructs a render output.
     */
    RenderOutput();

    /**
     * @brief Destroys the render output.
     */
    virtual ~RenderOutput();

    /**
     * @brief Returns the render pass description used by this output.
     */
    RenderSpec pass() const;

    /**
     * @brief Sets the render pass description used by this output.
     */
    void setRenderSpec(const RenderSpec& renderSpec);

    /**
     * @brief Receives a completed frame from the render engine.
     *
     * The default implementation does nothing. Derived output types can override
     * this to enqueue, write, transmit, or display a rendered frame.
     *
     * @param image      Rendered frame data.
     * @param frame      Monotonic frame index generated by the render engine.
     */
    virtual void enqueueFrame(const core::ImageBuffer& image, qint64 frame);

private:
    Q_DISABLE_COPY_MOVE(RenderOutput)
    QScopedPointer<RenderOutputPrivate> p;
};

}  // namespace flipman::sdk::render

/**
 * @note Registering the type for use in QVariant.
 */
Q_DECLARE_METATYPE(flipman::sdk::render::RenderOutput*)
